
export CHART = metrics-server
export MODULE = .
export NAMESPACE = kube-system
export REPO = metrics-server
export URL = https://kubernetes-sigs.github.io/metrics-server/
export VERSION = 3.8.2

include ../Makefile
